// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['WEB.API_KEY']!,
    appId: dotenv.env['WEB.APP_ID']!,
    messagingSenderId: dotenv.env['WEB.MESSAGING_SENDER_ID']!,
    projectId: dotenv.env['WEB.PROJECT_ID']!,
    authDomain: dotenv.env['WEB.AUTH_DOMAIN']!,
    storageBucket: dotenv.env['WEB.STORAGE_BUCKET']!,
    measurementId: dotenv.env['WEB.MEASUREMENT_ID']!,
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['ANDROID.API_KEY']!,
    appId: dotenv.env['ANDROID.APP_ID']!,
    messagingSenderId: dotenv.env['ANDROID.MESSAGING_SENDER_ID']!,
    projectId: dotenv.env['ANDROID.PROJECT_ID']!,
    storageBucket: dotenv.env['ANDROID.STORAGE_BUCKET']!,
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['IOS.API_KEY']!,
    appId: dotenv.env['IOS.APP_ID']!,
    messagingSenderId: dotenv.env['IOS.MESSAGING_SENDER_ID']!,
    projectId: dotenv.env['IOS.PROJECT_ID']!,
    storageBucket: dotenv.env['IOS.STORAGE_BUCKET']!,
    iosClientId: dotenv.env['IOS.IOS_CLIENT_ID']!,
    iosBundleId: dotenv.env['IOS.IOS_BUNDLE_ID']!,
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['MACOS.API_KEY']!,
    appId: dotenv.env['MACOS.APP_ID']!,
    messagingSenderId: dotenv.env['MACOS.MESSAGING_SENDER_ID']!,
    projectId: dotenv.env['MACOS.PROJECT_ID']!,
    storageBucket: dotenv.env['MACOS.STORAGE_BUCKET']!,
    iosClientId: dotenv.env['MACOS.IOS_CLIENT_ID']!,
    iosBundleId: dotenv.env['MACOS.IOS_BUNDLE_ID']!,
  );
}
